#page title
page_title                                : DashFacer                                 # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6748646518                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : DashFacer                                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your Racing Companion

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.
google_analytics_id                       : G-QQVZEPDS5B                              # Enter your Google Analytics ID to enable tracking. If you don't have one, leave empty.

# Information About Yourself
your_name                                 : Valerio Mazzeo                                
your_link                                 :                      
your_city                                 : Italy                                
email_address                             : support@dashfacer.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        :
x_username                                : valeriomazzeo
github_username                           : valeriomazzeo
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Real-Time Telemetry
    description                           : Live lap time, race position, sector deltas, and gap analysis — updated while you drive.
    fontawesome_icon_name                 : stopwatch
    
  - title                                 : Sector Delta
    description                           : See your gain or loss in each sector — get performance feedback before the lap is even finished.
    fontawesome_icon_name                 : plus-minus

  - title                                 : Multi-Class Position
    description                           : See your real-time ranking not only overall, but also within your class. Whether you’re racing amateurs, or pro drivers, you always know your position against the right competitors.
    fontawesome_icon_name                 : list-ol    

  - title                                 : Voice Feedback
    description                           : Hear your latest lap time or performance changes without taking your eyes off the track.
    fontawesome_icon_name                 : volume-up

  - title                                 : Steering Wheel Mount Friendly
    description                           : Designed for visibility and clarity from your wheel or dashboard.
    fontawesome_icon_name                 : car

  - title                                 : Optimized Dark UI
    description                           : High-contrast design for outdoor visibility and night racing.
    fontawesome_icon_name                 : adjust



# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 0.075
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.05

device_color                              : iPhone_16_Pro_Max                         # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#007AFF"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#007AFF"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
